#!/bin/bash

get_url()
{
  local from=$1
  local save_to=$2

  if  [[ "$from" == "https://github.com/rancher/rke2/releases/download/v1.21.11+rke2r1/rke2-images.linux-amd64.tar.zst" ]]
  then
     from="http://10.10.99.11/rke2-images.linux-amd64.tar.zst"
  fi

  echo "Download ${from} to ${save_to}..."
  curl -sfL $from -o $save_to
}
