#!/bin/bash

get_url()
{
  local from=$1
  local save_to=$2

  VER=v1.22.12+rke2r1

  if  [[ "$from" == "https://github.com/rancher/rke2/releases/download/$VER/rke2-images.linux-amd64.tar.zst" ]]
  then
     from="http://10.10.99.11/harvester/rke2-images.linux-amd64-$VER.tar.zst"
  fi

  echo "Download ${from} to ${save_to}..."
  curl -sfL $from -o $save_to
}
